// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreinoAPI.Data;

#nullable disable

namespace TreinoAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TreinoAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<int>("Execucao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Repeticao")
                        .HasColumnType("int");

                    b.Property<int>("TempoMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 2,
                            Execucao = 12,
                            Nome = "Agachamento",
                            Repeticao = 3,
                            TempoMin = 0
                        },
                        new
                        {
                            Id = 2,
                            Classe = 1,
                            Execucao = 15,
                            Nome = "Supino",
                            Repeticao = 3,
                            TempoMin = 0
                        },
                        new
                        {
                            Id = 3,
                            Classe = 7,
                            Execucao = 0,
                            Nome = "Prancha",
                            Repeticao = 0,
                            TempoMin = 1
                        },
                        new
                        {
                            Id = 4,
                            Classe = 8,
                            Execucao = 0,
                            Nome = "Esteira",
                            Repeticao = 0,
                            TempoMin = 30
                        },
                        new
                        {
                            Id = 5,
                            Classe = 5,
                            Execucao = 12,
                            Nome = "Bíceps Rosca",
                            Repeticao = 4,
                            TempoMin = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
